name: Quire checks

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: fedora

    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v6
        with:
          persist-credentials: false

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --locked --all-targets -- -D warnings

      - name: Test
        run: cargo test --locked --all-targets

